version: "3.3"

services:
  issuer_oidc:
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "6005:5000"
    volumes:
      - ./config.json:/config.json:ro
      - ../log-oidc/:/tmp/oidc_log_dev/
    restart: unless-stopped
